/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExpenseCategory = { 'entertainment' : null } |
  { 'food' : null } |
  { 'rent' : null } |
  { 'transport' : null } |
  { 'others' : null } |
  { 'health' : null };
export interface ExpenseEntry {
  'id' : bigint,
  'date' : string,
  'description' : string,
  'category' : ExpenseCategory,
  'amount' : number,
  'monthYear' : string,
}
export interface MonthlySummary {
  'totalIncome' : number,
  'totalSpent' : number,
  'savings' : number,
}
export interface UserProfile { 'monthlyIncome' : number }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExpense' : ActorMethod<
    [ExpenseCategory, number, string, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteExpense' : ActorMethod<[string, bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpensesForMonth' : ActorMethod<[string], Array<ExpenseEntry>>,
  'getMonthlyIncome' : ActorMethod<[], [] | [number]>,
  'getMonthlySummary' : ActorMethod<[string], MonthlySummary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setMonthlyIncome' : ActorMethod<[number], undefined>,
  'updateExpense' : ActorMethod<
    [bigint, ExpenseCategory, number, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];