/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExpenseCategory = IDL.Variant({
  'entertainment' : IDL.Null,
  'food' : IDL.Null,
  'rent' : IDL.Null,
  'transport' : IDL.Null,
  'others' : IDL.Null,
  'health' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'monthlyIncome' : IDL.Float64 });
export const ExpenseEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : ExpenseCategory,
  'amount' : IDL.Float64,
  'monthYear' : IDL.Text,
});
export const MonthlySummary = IDL.Record({
  'totalIncome' : IDL.Float64,
  'totalSpent' : IDL.Float64,
  'savings' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpense' : IDL.Func(
      [ExpenseCategory, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExpense' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpensesForMonth' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExpenseEntry)],
      ['query'],
    ),
  'getMonthlyIncome' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
  'getMonthlySummary' : IDL.Func([IDL.Text], [MonthlySummary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMonthlyIncome' : IDL.Func([IDL.Float64], [], []),
  'updateExpense' : IDL.Func(
      [IDL.Nat, ExpenseCategory, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExpenseCategory = IDL.Variant({
    'entertainment' : IDL.Null,
    'food' : IDL.Null,
    'rent' : IDL.Null,
    'transport' : IDL.Null,
    'others' : IDL.Null,
    'health' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'monthlyIncome' : IDL.Float64 });
  const ExpenseEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : ExpenseCategory,
    'amount' : IDL.Float64,
    'monthYear' : IDL.Text,
  });
  const MonthlySummary = IDL.Record({
    'totalIncome' : IDL.Float64,
    'totalSpent' : IDL.Float64,
    'savings' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpense' : IDL.Func(
        [ExpenseCategory, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExpense' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpensesForMonth' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExpenseEntry)],
        ['query'],
      ),
    'getMonthlyIncome' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
    'getMonthlySummary' : IDL.Func([IDL.Text], [MonthlySummary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMonthlyIncome' : IDL.Func([IDL.Float64], [], []),
    'updateExpense' : IDL.Func(
        [IDL.Nat, ExpenseCategory, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };